---
- name: Stop LAMP services in Amazon Linux
  hosts: localhost
  become: yes

  tasks:
    - name: Stop and disable httpd
      ansible.builtin.systemd_service:
        name: httpd
        state: stopped
        enabled: false

    - name: Stop and disable mariadb
      ansible.builtin.systemd_service:
        name: mariadb
        state: stopped
        enabled: false

    - name: Stop and disable php-fpm
      ansible.builtin.systemd_service:
        name: php-fpm
        state: stopped
        enabled: false